name: Build AlwaysEnglish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install full Qt using Aqtinstall
      shell: cmd
      run: |
        pip install aqtinstall
        aqt install-qt windows desktop 6.6.3 win64_msvc2019_64 --outputdir D:\Qt
    
    - name: Configure and Build
      shell: cmd
      run: |
        set PATH=D:\Qt\6.6.3\msvc2019_64\bin;%PATH%
        mkdir build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=D:\Qt\6.6.3\msvc2019_64 -DCMAKE_BUILD_TYPE=Release -GNinja
        ninja
    
    - name: Copy Qt dependencies
      shell: cmd
      run: |
        set PATH=D:\Qt\6.6.3\msvc2019_64\bin;%PATH%
        mkdir dist
        copy build\dist\AlwaysEnglish.exe dist\
        windeployqt dist\AlwaysEnglish.exe --qmldir=src\qml
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: AlwaysEnglish-Win64
        path: dist/